### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by yosiaki0113** [yosiaki0113/chat-space#9]
# IPアドレス
52.68.161.126

**Comment by miyu-yamamoto** [comment]
佐々木さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**① サイドバーの下線を表示させなくしましょう
② メッセージ送信フォームにカーソルを当てた時添付ファイルを選択するアイコンも青枠内に表示させましょう**
<img width="794" alt="スクリーンショット 2020-06-16 10 37 56" src="https://user-images.githubusercontent.com/59544869/84722283-b34bf200-afbd-11ea-8acd-7c741964d631.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by yosiaki0113** [comment]
ご確認いただきありがとうございます。

### ご指摘いただいた下記箇所を修正しました。

> ① サイドバーの下線を表示させなくしましょう

> ② メッセージ送信フォームにカーソルを当てた時添付ファイルを選択するアイコンも青枠内に表示させましょう

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
※今後実装に関する質問がありましたら、メンターに確認をお願いします！
